/** Mirrors the backend registry for display-only purposes. */
export const TOOL_LABELS = [
  { toolName: 'getOrder', label: 'Get Order', permission: 'READ_ORDERS' },
  { toolName: 'getCustomer', label: 'Get Customer', permission: 'READ_CUSTOMER' },
  { toolName: 'updateOrder', label: 'Update Order', permission: 'WRITE_ORDERS' },
  { toolName: 'deleteOrder', label: 'Delete Order', permission: 'DELETE_ORDERS' },
  { toolName: 'getPayroll', label: 'Get Payroll', permission: 'READ_PAYROLL' },
  { toolName: 'getEmployee', label: 'Get Employee', permission: 'READ_EMPLOYEE' },
  { toolName: 'getLeaveBalance', label: 'Get Leave Balance', permission: 'READ_LEAVE' },
  { toolName: 'updateEmployee', label: 'Update Employee', permission: 'WRITE_EMPLOYEE' },
  { toolName: 'deleteEmployee', label: 'Delete Employee', permission: 'DELETE_EMPLOYEE' },
  { toolName: 'getInvoice', label: 'Get Invoice', permission: 'READ_INVOICES' },
  { toolName: 'getPayment', label: 'Get Payment', permission: 'READ_PAYMENTS' },
  { toolName: 'updateInvoice', label: 'Update Invoice', permission: 'WRITE_INVOICES' },
  { toolName: 'deleteInvoice', label: 'Delete Invoice', permission: 'DELETE_INVOICES' },
  { toolName: 'getEmployeeSalary', label: 'Get Employee Salary', permission: 'READ_SALARY' },
  { toolName: 'getProduct', label: 'Get Product', permission: 'READ_PRODUCTS' },
  { toolName: 'getStock', label: 'Get Stock', permission: 'READ_STOCK' },
  { toolName: 'updateStock', label: 'Update Stock', permission: 'WRITE_STOCK' },
  { toolName: 'deleteProduct', label: 'Delete Product', permission: 'DELETE_PRODUCTS' },
  { toolName: 'updateProductPrice', label: 'Update Product Price', permission: 'WRITE_PRICES' },
  { toolName: 'getCampaign', label: 'Get Campaign', permission: 'READ_CAMPAIGNS' },
  { toolName: 'getCampaignMetrics', label: 'Get Campaign Metrics', permission: 'READ_CAMPAIGN_METRICS' },
  { toolName: 'updateCampaign', label: 'Update Campaign', permission: 'WRITE_CAMPAIGNS' },
  { toolName: 'deleteCampaign', label: 'Delete Campaign', permission: 'DELETE_CAMPAIGNS' },
  { toolName: 'getEmployeeData', label: 'Get Employee Data', permission: 'READ_EMPLOYEE_DATA' },
  { toolName: 'getAppointment', label: 'Get Appointment', permission: 'READ_APPOINTMENTS' },
  { toolName: 'getAvailableSlots', label: 'Get Available Slots', permission: 'READ_SLOTS' },
  { toolName: 'createAppointment', label: 'Create Appointment', permission: 'CREATE_APPOINTMENTS' },
  { toolName: 'updateAppointment', label: 'Update Appointment', permission: 'WRITE_APPOINTMENTS' },
  { toolName: 'deleteAppointment', label: 'Delete Appointment', permission: 'DELETE_APPOINTMENTS' },
  { toolName: 'getInventory', label: 'Get Inventory', permission: 'READ_INVENTORY' },
  { toolName: 'issueRefund', label: 'Issue Refund', permission: 'ISSUE_REFUND' },
];
